'use strict'

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    return queryInterface.bulkInsert('Checkpoints', [
      {
        checkpoint_id: 1,
        checkpoint_name: 'Автомобильный пункт пропуска Борисоглебск',
        address: 'Мурманская область, Р-21 Кола, 1592-й километр, 21',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'Борисоглебск',
        region: 'Мурманская область',
        checkpoint_type_id: 1,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 30.207738,
        lng: 69.647649,
      },
      {
        checkpoint_id: 2,
        checkpoint_name: 'СЫКТЫВКАР',
        address: 'Республика Коми, Сыктывкар, Советская улица, 88',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'городской округ Сыктывкар',
        region: 'Республика Коми',
        checkpoint_type_id: 4,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 50.851616,
        lng: 61.663895,
      },
      {
        checkpoint_id: 3,
        checkpoint_name: 'Автомобильный пункт пропуска Нижний Зарамаг',
        address: 'Республика Северная Осетия — Алания, Алагирский район, село Нар',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'Алагирский район',
        region: 'Республика Северная Осетия — Алания',
        checkpoint_type_id: 1,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 44.021635,
        lng: 42.679979,
      },
      {
        checkpoint_id: 4,
        checkpoint_name: 'Железнодорожный пункт пропуска Черняховск',
        address: 'Калининградская область, Черняховск',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'Черняховский муниципальный округ',
        region: 'Калининградская область',
        checkpoint_type_id: 2,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 21.819503,
        lng: 54.630706,
      },
      {
        checkpoint_id: 5,
        checkpoint_name: 'Автомобильный пункт пропуска Адлер',
        address: 'Краснодарский край, Сочи, Урожайная улица, 101',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'городской округ Сочи',
        region: 'Краснодарский край',
        checkpoint_type_id: 1,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 40.005941,
        lng: 43.395202,
      },
      {
        checkpoint_id: 6,
        checkpoint_name: 'Железнодорожный пункт пропуска Адлер',
        address: 'Краснодарский край, Сочи, Урожайная улица, 101',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'городской округ Сочи',
        region: 'Краснодарский край',
        checkpoint_type_id: 2,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 39.993023,
        lng: 43.401916,
      },
      {
        checkpoint_id: 7,
        checkpoint_name: 'Международный аэропорт Сочи имени В. И. Севастьянова',
        address: 'Краснодарский край, городской округ Сочи, аэропорт Сочи имени В.И. Севастьянова',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'городской округ Сочи',
        region: 'Краснодарский край',
        checkpoint_type_id: 4,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 39.941325,
        lng: 43.44837,
      },
      {
        checkpoint_id: 8,
        checkpoint_name: 'Морской пункт пропуска Кандалакша',
        address: 'Мурманская область, городское поселение Кандалакша, Кандалакша, Беломорская улица, 19',
        branch_id: 1,
        neighboring_state_id: 1,
        district: 'Кандалакшский район',
        region: 'Мурманская область',
        checkpoint_type_id: 3,
        working_hours_id: 1,
        operating_mode_id: 1,
        lat: 32.413156,
        lng: 67.137666,
      },
    ])
  },

  async down(queryInterface) {
    return queryInterface.bulkDelete('Checkpoints', null, {})
  },
}
