'use strict'

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    return queryInterface.bulkInsert('Orders', [
      {
        order_id: 1,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-24'),
        task_end_datetime: new Date('2024-01-25'),
        priority_id: 1,
      },
      {
        order_id: 2,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-24'),
        task_end_datetime: new Date('2024-01-25'),
        priority_id: 1,
      },
      {
        order_id: 3,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-23'),
        task_end_datetime: new Date('2024-01-24'),
        priority_id: 1,
      },
      {
        order_id: 4,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-25'),
        task_end_datetime: new Date('2024-01-26'),
        priority_id: 1,
      },
      {
        order_id: 5,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-21'),
        task_end_datetime: new Date('2024-01-22'),
        priority_id: 1,
      },
      {
        order_id: 6,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-22'),
        task_end_datetime: new Date('2024-01-23'),
        priority_id: 1,
      },
      {
        order_id: 7,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-23'),
        task_end_datetime: new Date('2024-01-24'),
        priority_id: 1,
      },
      {
        order_id: 8,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-24'),
        task_end_datetime: new Date('2024-01-25'),
        priority_id: 1,
      },
      {
        order_id: 9,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-25'),
        task_end_datetime: new Date('2024-01-26'),
        priority_id: 1,
      },
      {
        order_id: 10,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-26'),
        task_end_datetime: new Date('2024-01-27'),
        priority_id: 1,
      },
      {
        order_id: 11,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-27'),
        task_end_datetime: new Date('2024-01-28'),
        priority_id: 1,
      },
      {
        order_id: 12,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-28'),
        task_end_datetime: new Date('2024-01-29'),
        priority_id: 1,
      },
      {
        order_id: 13,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-29'),
        task_end_datetime: new Date('2024-01-30'),
        priority_id: 1,
      },
      {
        order_id: 14,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-01-30'),
        task_end_datetime: new Date('2024-01-31'),
        priority_id: 1,
      },
      {
        order_id: 15,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-01'),
        task_end_datetime: new Date('2024-02-02'),
        priority_id: 1,
      },
      {
        order_id: 16,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-02'),
        task_end_datetime: new Date('2024-02-03'),
        priority_id: 1,
      },
      {
        order_id: 17,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-03'),
        task_end_datetime: new Date('2024-02-04'),
        priority_id: 1,
      },
      {
        order_id: 18,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-04'),
        task_end_datetime: new Date('2024-02-05'),
        priority_id: 1,
      },
      {
        order_id: 19,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-06'),
        task_end_datetime: new Date('2024-02-07'),
        priority_id: 1,
      },
      {
        order_id: 20,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-08'),
        task_end_datetime: new Date('2024-02-09'),
        priority_id: 1,
      },
      {
        order_id: 21,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-09'),
        task_end_datetime: new Date('2024-02-10'),
        priority_id: 1,
      },
      {
        order_id: 22,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-10'),
        task_end_datetime: new Date('2024-02-11'),
        priority_id: 1,
      },
      {
        order_id: 23,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-12'),
        task_end_datetime: new Date('2024-02-13'),
        priority_id: 1,
      },
      {
        order_id: 24,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-13'),
        task_end_datetime: new Date('2024-02-14'),
        priority_id: 1,
      },
      {
        order_id: 25,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-14'),
        task_end_datetime: new Date('2024-02-15'),
        priority_id: 1,
      },
      {
        order_id: 26,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-15'),
        task_end_datetime: new Date('2024-02-16'),
        priority_id: 1,
      },
      {
        order_id: 27,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-16'),
        task_end_datetime: new Date('2024-02-17'),
        priority_id: 1,
      },
      {
        order_id: 28,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-17'),
        task_end_datetime: new Date('2024-02-18'),
        priority_id: 1,
      },
      {
        order_id: 29,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-18'),
        task_end_datetime: new Date('2024-02-19'),
        priority_id: 1,
      },
      {
        order_id: 30,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-20'),
        task_end_datetime: new Date('2024-02-21'),
        priority_id: 1,
      },
      {
        order_id: 31,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-21'),
        task_end_datetime: new Date('2024-02-22'),
        priority_id: 1,
      },
      {
        order_id: 32,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-22'),
        task_end_datetime: new Date('2024-02-23'),
        priority_id: 1,
      },
      {
        order_id: 33,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-23'),
        task_end_datetime: new Date('2024-02-24'),
        priority_id: 1,
      },
      {
        order_id: 34,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-24'),
        task_end_datetime: new Date('2024-02-25'),
        priority_id: 1,
      },
      {
        order_id: 35,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-25'),
        task_end_datetime: new Date('2024-02-26'),
        priority_id: 1,
      },
      {
        order_id: 36,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-26'),
        task_end_datetime: new Date('2024-02-27'),
        priority_id: 1,
      },
      {
        order_id: 37,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-27'),
        task_end_datetime: new Date('2024-02-28'),
        priority_id: 1,
      },
      {
        order_id: 38,
        order_name: 'Уборка снега',
        order_description: 'Уборка снега возле входа в котельную',
        facility_id: 1,
        executor_id: 5,
        completed_by: 5,
        creator_id: 1,
        order_status_id: 1,
        planned_datetime: new Date('2024-02-28'),
        task_end_datetime: new Date('2024-02-29'),
        priority_id: 1,
      },
    ])
  },

  async down(queryInterface) {
    return queryInterface.bulkDelete('Orders', null, {})
  },
}
