export const AppStrings = {
  PROJECT_NAME: 'ГРАВИТИНО АСУУП',
  ASC: 'ASC',

  ORGANIZATION: 'Организация',
  ORGANIZATION_TYPE: 'Тип организации',
  CATEGORY: 'Категория',
  CHECKPOINT: 'Пункт пропуска',
  ORDER: 'Заказ',
  ORDER_STATUS: 'Статус заказа',
  ORDER_PRIORITY: 'Приоритет',
  ORDER_EXECUTOR: 'Выполнен (кем)',
  ORDER_CREATOR: 'Создатель заказа',
  TASK: 'Задача',
  FILE_TYPE: 'Заказ',
  FACILITY: 'Объект обслуживания',
  BRANCH: 'Филиал',
  NEIGHBORING_STATE: 'Приграничное государство',
  WORKING_HOURS: 'Часы работы',
  OPERATING_MODE: 'Режим работы',
  USER_HISTORY: 'Пользовтель выполнивший действие',
  PERIODICITY: 'Периодичность задачи',
  PROPERTY_NAME: 'Название характеристики',
  PROPERTY_VALUE: 'Занчение характеристики',
  PERMISSION: 'Разрешение',
  PERMISSION_STATUS: 'Статус разрешения',
  PERSON: 'Данные пользователя',
  USER: 'Пользователь',
  USER_STATUS: 'Статус пользователя',
  GROUP: 'Группа',

  BRANCH_NAME_EXAMPLE: 'Филиал №1',
  BRANCH_NAME_DESCRIPTION: 'Название филиала',
  BRANCH_ADDRESS_EXAMPLE: 'улица У.',
  BRANCH_ADDRESS_DESCRIPTION: 'Адрес филиала',
  BRANCH_CREATED_RESPONSE: 'Филиал создан',
  BRANCH_CREATE_OPERATION: 'Создание филиала',
  BRANCH_ALL_RESPONSE: 'Список филиалов получен',
  BRANCH_ALL_OPERATION: 'Получение списка всех филиалов',
  BRANCH_UPDATE_RESPONSE: 'Филиал изменен',
  BRANCH_UPDATE_OPERATION: 'Изменение филиала',
  BRANCH_DELETE_RESPONSE: 'Филиал удален',
  BRANCH_DELETE_OPERATION: 'Удаление филиала',
  BRANCH_IMPORT_RESPONSE: 'Филиалы импортированы',
  BRANCH_IMPORT_OPERATION: 'Импорт филиалов',
  BRANCH_IMPORT_UPLOAD_RESPONSE: 'Файл импорта загружен',
  BRANCH_IMPORT_UPLOAD_OPERATION: 'Импорт филиалов',

  CATEGORY_NAME_EXAMPLE: 'Категория №1',
  CATEGORY_NAME_DESCRIPTION: 'Название категории',
  CATEGORY_CREATED_RESPONSE: 'Категория создана',
  CATEGORY_CREATE_OPERATION: 'Создание категории',
  CATEGORY_ALL_RESPONSE: 'Список категорий получен',
  CATEGORY_ALL_OPERATION: 'Получение списка всех категорий',
  CATEGORY_UPDATE_RESPONSE: 'Категория изменена',
  CATEGORY_UPDATE_OPERATION: 'Изменение категории',
  CATEGORY_DELETE_RESPONSE: 'Категория удалена',
  CATEGORY_DELETE_OPERATION: 'Удаление категории',

  CHECKPOINT_NAME_EXAMPLE: 'Пункт пропуска №1',
  CHECKPOINT_NAME_DESCRIPTION: 'Название пункта пропуска',
  CHECKPOINT_ADDRESS_EXAMPLE: 'улица У.',
  CHECKPOINT_ADDRESS_DESCRIPTION: 'Адрес пункта пропуска',
  CHECKPOINT_DISTRICT_EXAMPLE: 'Округ ...',
  CHECKPOINT_DISTRICT_DESCRIPTION: 'Округ пункта пропуска',
  CHECKPOINT_REGION_EXAMPLE: 'Москва',
  CHECKPOINT_REGION_DESCRIPTION: 'Область пункта пропуска',
  CHECKPOINT_CREATED_RESPONSE: 'Пункт пропуска создан',
  CHECKPOINT_CREATE_OPERATION: 'Создание пункта пропуска',
  CHECKPOINT_ALL_RESPONSE: 'Список пунктов пропуска получен',
  CHECKPOINT_ALL_OPERATION: 'Получение списка всех пунктов пропуска',
  CHECKPOINT_ALL_BY_BRANCH_RESPONSE: 'Список пунктов пропуска по ID филиала получен',
  CHECKPOINT_ALL_BY_BRANCH_OPERATION: 'Получение списка всех пунктов пропуска по ID филиала',
  CHECKPOINT_UPDATE_RESPONSE: 'Пункт пропуска изменен',
  CHECKPOINT_UPDATE_OPERATION: 'Изменение пункта пропуска',
  CHECKPOINT_DELETE_RESPONSE: 'Пункт пропуска удален',
  CHECKPOINT_DELETE_OPERATION: 'Удаление пункта пропуска',

  CHECKPOINT_TYPE_NAME_EXAMPLE: 'Тип пункта пропуска',
  CHECKPOINT_TYPE_NAME_DESCRIPTION: 'Тип пункта пропуска',
  CHECKPOINT_TYPE_CREATED_RESPONSE: 'Тип пункта пропуска создан',
  CHECKPOINT_TYPE_CREATE_OPERATION: 'Создание типа пункта пропуска',
  CHECKPOINT_TYPE_ALL_RESPONSE: 'Список типов пунктов пропуска получен',
  CHECKPOINT_TYPE_ALL_OPERATION: 'Получение списка всех типов пунктов пропуска',
  CHECKPOINT_TYPE_UPDATE_RESPONSE: 'Тип пункта пропуска изменен',
  CHECKPOINT_TYPE_UPDATE_OPERATION: 'Изменение типа пункта пропуска',
  CHECKPOINT_TYPE_DELETE_RESPONSE: 'Тип пункта пропуска удален',
  CHECKPOINT_TYPE_DELETE_OPERATION: 'Удаление типа пункта пропуска',

  FACILITY_NAME_EXAMPLE: 'Котельная №1',
  FACILITY_NAME_DESCRIPTION: 'Название объекта обслуживания',
  FACILITY_CREATED_RESPONSE: 'Объект обслуживания создан',
  FACILITY_CREATE_OPERATION: 'Создание объекта обслуживания',
  FACILITY_ALL_RESPONSE: 'Список объектов обслуживания получен',
  FACILITY_ALL_OPERATION: 'Получение списка всех объектов обслуживания',
  FACILITY_ALL_BY_CHECKPOINT_RESPONSE: 'Список объектов обслуживания по ID пунтка пропуска получен',
  FACILITY_ALL_BY_CHECKPOINT_OPERATION: 'Получение списка всех объектов обслуживания по ID пунтка пропуска',
  FACILITY_ALL_BY_BRANCH_RESPONSE: 'Список объектов обслуживания по ID филиала получен',
  FACILITY_ALL_BY_BRANCH_OPERATION: 'Получение списка всех объектов обслуживания по ID филиала',
  FACILITY_UPDATE_RESPONSE: 'Объект обслуживания изменен',
  FACILITY_UPDATE_OPERATION: 'Изменение объекта обслуживания',
  FACILITY_DELETE_RESPONSE: 'Объект обслуживания удален',
  FACILITY_DELETE_OPERATION: 'Удаление объекта обслуживания',

  FACILITY_TYPE_EXAMPLE: 'Котельная №1',
  FACILITY_TYPE_DESCRIPTION: 'Название типа объекта обслуживания',
  FACILITY_TYPE_CREATED_RESPONSE: 'Тип объекта обслуживания создан',
  FACILITY_TYPE_CREATE_OPERATION: 'Создание типа объекта обслуживания',
  FACILITY_TYPE_ALL_RESPONSE: 'Список типов объектов обслуживания получен',
  FACILITY_TYPE_ALL_OPERATION: 'Получение списка всех типов объектов обслуживания',
  FACILITY_TYPE_UPDATE_RESPONSE: 'Тип объекта обслуживания изменен',
  FACILITY_TYPE_UPDATE_OPERATION: 'Изменение типа объекта обслуживания',
  FACILITY_TYPE_DELETE_RESPONSE: 'Тип объекта обслуживания удален',
  FACILITY_TYPE_DELETE_OPERATION: 'Удаление типа объекта обслуживания',

  FILE_TYPE_NAME_EXAMPLE: 'Фотография',
  FILE_TYPE_NAME_DESCRIPTION: 'Тип файла',
  FILE_TYPE_EXTENSION_EXAMPLE: '.xls',
  FILE_TYPE_EXTENSION_DESCRIPTION: 'Расширение файла',
  FILE_TYPE_CREATED_RESPONSE: 'Тип файла создан',
  FILE_TYPE_CREATE_OPERATION: 'Создание типа файла',
  FILE_TYPE_ALL_RESPONSE: 'Список типов файлов получен',
  FILE_TYPE_ALL_OPERATION: 'Получение списка всех типов файлов',
  FILE_TYPE_UPDATE_RESPONSE: 'Тип файла изменен',
  FILE_TYPE_UPDATE_OPERATION: 'Изменение типа файла',
  FILE_TYPE_DELETE_RESPONSE: 'Тип файла удален',
  FILE_TYPE_DELETE_OPERATION: 'Удаление типа файла',

  FILE_CREATED_RESPONSE: 'Файл загружен',
  FILE_CREATE_OPERATION: 'Загрузка файлов',

  GROUP_NAME_EXAMPLE: 'Группа №1',
  GROUP_NAME_DESCRIPTION: 'Название группы',
  GROUP_CREATED_RESPONSE: 'Группа создана',
  GROUP_CREATE_OPERATION: 'Создание группы',
  GROUP_ALL_RESPONSE: 'Список групп получен',
  GROUP_ALL_OPERATION: 'Получение списка всех групп',
  GROUP_UPDATE_RESPONSE: 'Группа изменена',
  GROUP_UPDATE_OPERATION: 'Изменение группы',
  GROUP_DELETE_RESPONSE: 'Группа удалена',
  GROUP_DELETE_OPERATION: 'Удаление группы',

  NEIGHBORING_STATE_NAME_EXAMPLE: 'Китай',
  NEIGHBORING_STATE_NAME_DESCRIPTION: 'Приграничное государство',
  NEIGHBORING_STATE_CREATED_RESPONSE: 'Приграничное гос-во создано',
  NEIGHBORING_STATE_CREATE_OPERATION: 'Создание приграничного гос-ва',
  NEIGHBORING_STATE_ALL_RESPONSE: 'Список приграничных государств получен',
  NEIGHBORING_STATE_ALL_OPERATION: 'Получение списка всех приграничных государств',
  NEIGHBORING_STATE_UPDATE_RESPONSE: 'Приграничное гос-во изменено',
  NEIGHBORING_STATE_UPDATE_OPERATION: 'Изменение приграничного гос-ва',
  NEIGHBORING_STATE_DELETE_RESPONSE: 'Приграничное гос-во удалено',
  NEIGHBORING_STATE_DELETE_OPERATION: 'Удаление приграничного гос-ва',

  OPERATING_MODE_NAME_EXAMPLE: 'Постоянный',
  OPERATING_MODE_NAME_DESCRIPTION: 'Режим работы',
  OPERATING_MODE_CREATED_RESPONSE: 'Режим работы создан',
  OPERATING_MODE_CREATE_OPERATION: 'Создание режима работы',
  OPERATING_MODE_ALL_RESPONSE: 'Список режимов работы получен',
  OPERATING_MODE_ALL_OPERATION: 'Получение списка всех режимов работы',
  OPERATING_MODE_UPDATE_RESPONSE: 'Режим работы изменен',
  OPERATING_MODE_UPDATE_OPERATION: 'Изменение режима работы',
  OPERATING_MODE_DELETE_RESPONSE: 'Режим работы удален',
  OPERATING_MODE_DELETE_OPERATION: 'Удаление режима работы',

  ORDER_CREATED_RESPONSE: 'Заказ создан',
  ORDER_CREATE_OPERATION: 'Создание заказа',
  ORDER_ALL_RESPONSE: 'Список заказов получен',
  ORDER_ALL_OPERATION: 'Получение списка всех заказов',
  ORDER_ALL_BY_BRANCH_RESPONSE: 'Список заказов получен',
  ORDER_ALL_BY_BRANCH_OPERATION: 'Получение списка всех заказов по ID филиалов',
  ORDER_ALL_BY_CHECKPOINT_RESPONSE: 'Список заказов получен',
  ORDER_ALL_BY_CHECKPOINT_OPERATION: 'Получение списка всех заказов по ID пунтков пропуска',
  ORDER_ALL_MY_RESPONSE: 'Список заказов получен',
  ORDER_ALL_MY_OPERATION: 'Получение списка всех заказов пользователя',
  ORDER_UPDATE_RESPONSE: 'Заказ изменен',
  ORDER_UPDATE_OPERATION: 'Изменение заказа',
  ORDER_STATUS_UPDATE_RESPONSE: 'Статус заказа изменен',
  ORDER_STATUS_UPDATE_OPERATION: 'Изменение статуса заказа',
  ORDER_DELETE_RESPONSE: 'Заказ удален',
  ORDER_DELETE_OPERATION: 'Удаление заказа',

  ORDER_JOURNAL_COMMENT_EXAMPLE: 'Изменен статус заказа',
  ORDER_JOURNAL_COMMENT_DESCRIPTION: 'Название действия',
  ORDER_JOURNAL_FIELD_EXAMPLE: 'order_name',
  ORDER_JOURNAL_FIELD_DESCRIPTION: 'Измененное поле',
  ORDER_JOURNAL_OLD_VALUE_EXAMPLE: 'Заказ №1',
  ORDER_JOURNAL_OLD_VALUE_DESCRIPTION: 'Старое значение',
  ORDER_JOURNAL_NEW_VALUE_EXAMPLE: 'Заказ №2',
  ORDER_JOURNAL_NEW_VALUE_DESCRIPTION: 'Новое значение',
  ORDER_JOURNAL_ALL_RESPONSE: 'Журнал по заказу получен',
  ORDER_JOURNAL_ALL_OPERATION: 'Получение журнала заказа',

  ORDER_STATUS_NAME_EXAMPLE: 'Выполнено',
  ORDER_STATUS_NAME_DESCRIPTION: 'Статус заказа',
  ORDER_STATUS_CREATED_RESPONSE: 'Статус заказа создан',
  ORDER_STATUS_CREATE_OPERATION: 'Создание статуса заказа',
  ORDER_STATUS_ALL_RESPONSE: 'Список статусов заказа получен',
  ORDER_STATUS_ALL_OPERATION: 'Получение списка всех статусов заказа',
  ORDER_STATUS_DELETE_RESPONSE: 'Статус заказа удален',
  ORDER_STATUS_DELETE_OPERATION: 'Удаление статуса заказа',

  ORGANIZATION_CREATED_RESPONSE: 'Организация создана',
  ORGANIZATION_CREATE_OPERATION: 'Создание организации',
  ORGANIZATION_ALL_RESPONSE: 'Список организаций получен',
  ORGANIZATION_ALL_OPERATION: 'Получение списка всех организаций',
  ORGANIZATION_ALL_BY_CHECKPOINT_RESPONSE: 'Список организаций получен',
  ORGANIZATION_ALL_BY_CHECKPOINT_OPERATION: 'Получение списка всех организаций по пункту пропуска',
  ORGANIZATION_UPDATE_RESPONSE: 'Организация изменена',
  ORGANIZATION_UPDATE_OPERATION: 'Изменение организации',
  ORGANIZATION_DELETE_RESPONSE: 'Организация удалена',
  ORGANIZATION_DELETE_OPERATION: 'Удаление организации',

  ORGANIZATION_TYPE_NAME_EXAMPLE: 'Уборка, ремонт',
  ORGANIZATION_TYPE_NAME_DESCRIPTION: 'Вид деятельности организации',
  ORGANIZATION_TYPE_CREATED_RESPONSE: 'Вид деятельности организации создан',
  ORGANIZATION_TYPE_CREATE_OPERATION: 'Создание вида деятельности организации',
  ORGANIZATION_TYPE_ALL_RESPONSE: 'Список видов деятельности организаций получен',
  ORGANIZATION_TYPE_ALL_OPERATION: 'Получение списка всех видов деятельностей организаций',
  ORGANIZATION_TYPE_UPDATE_RESPONSE: 'Вид деятельности организации изменен',
  ORGANIZATION_TYPE_UPDATE_OPERATION: 'Изменение вида деятельности организации',
  ORGANIZATION_TYPE_DELETE_RESPONSE: 'Вид деятельности организации удален',
  ORGANIZATION_TYPE_DELETE_OPERATION: 'Удаление вида деятельности организации',

  PERIODICITY_ALL_RESPONSE: 'Список периодичностей задач получен',
  PERIODICITY_ALL_OPERATION: 'Получение списка всех периодичностей задач',

  PERMISSIONS_SKU_EXAMPLE: 'category-create',
  PERMISSIONS_SKU_DESCRIPTION: 'SKU разрешения',
  PERMISSIONS_NAME_EXAMPLE: 'Создание категорий',
  PERMISSIONS_NAME_DESCRIPTION: 'Название разрешения',
  PERMISSIONS_DESC_EXAMPLE: 'Описание',
  PERMISSIONS_DESC_DESCRIPTION: 'Описание разрешения',
  PERMISSIONS_ENTITY_NAME_EXAMPLE: 'Organizations',
  PERMISSIONS_ENTITY_NAME_DESCRIPTION: 'Название таблицы',

  PERSON_LAST_NAME_EXAMPLE: 'Иванов',
  PERSON_LAST_NAME_DESCRIPTION: 'Фамилия пользователя',
  PERSON_FIRST_NAME_EXAMPLE: 'Иван',
  PERSON_FIRST_NAME_DESCRIPTION: 'Имя пользователя',
  PERSON_PATRONYMIC_NAME_EXAMPLE: 'Иванович',
  PERSON_PATRONYMIC_NAME_DESCRIPTION: 'Отчество пользователя',
  PERSON_ALL_RESPONSE: 'Список данных пользователей получен',
  PERSON_ALL_OPERATION: 'Получение списка всех данных пользователей пользователей',

  PRIORITY_NAME_EXAMPLE: 'Ежедневно',
  PRIORITY_NAME_DESCRIPTION: 'Название приоритета',
  PRIORITY_CREATED_RESPONSE: 'Приоритет создан',
  PRIORITY_CREATE_OPERATION: 'Создание приоритета',
  PRIORITY_ALL_RESPONSE: 'Список приоритетов получен',
  PRIORITY_ALL_OPERATION: 'Получение списка всех приоритетов',
  PRIORITY_UPDATE_RESPONSE: 'Приоритет изменен',
  PRIORITY_UPDATE_OPERATION: 'Изменение приоритета',
  PRIORITY_DELETE_RESPONSE: 'Приоритет удален',
  PRIORITY_DELETE_OPERATION: 'Удаление приоритета',

  PROPERTY_CREATED_RESPONSE: 'Характеристика создана',
  PROPERTY_CREATE_OPERATION: 'Создание характеристики',
  PROPERTY_ALL_RESPONSE: 'Список характеристик получен',
  PROPERTY_ALL_OPERATION: 'Получение списка всех характеристик',
  PROPERTY_UPDATE_RESPONSE: 'Характеристика изменена',
  PROPERTY_UPDATE_OPERATION: 'Изменение характеристики',
  PROPERTY_DELETE_RESPONSE: 'Характеристика удалена',
  PROPERTY_DELETE_OPERATION: 'Удаление характеристики',

  PROPERTY_NAME_EXAMPLE: 'Характеристика',
  PROPERTY_NAME_DESCRIPTION: 'Название характеристики',
  PROPERTY_NAME_CREATED_RESPONSE: 'Название характеристики создано',
  PROPERTY_NAME_CREATE_OPERATION: 'Создание названия характеристики',
  PROPERTY_NAME_ALL_RESPONSE: 'Список названий характеристик получен',
  PROPERTY_NAME_ALL_OPERATION: 'Получение списка всех названий характеристик',
  PROPERTY_NAME_UPDATE_RESPONSE: 'Название характеристики изменено',
  PROPERTY_NAME_UPDATE_OPERATION: 'Изменение названия характеристики',
  PROPERTY_NAME_DELETE_RESPONSE: 'Название характеристики удалено',
  PROPERTY_NAME_DELETE_OPERATION: 'Удаление названия характеристики',

  PROPERTY_VALUE_EXAMPLE: '10',
  PROPERTY_VALUE_DESCRIPTION: 'Значение характеристик',
  PROPERTY_VALUE_CREATED_RESPONSE: 'Значение характеристики создано',
  PROPERTY_VALUE_CREATE_OPERATION: 'Создание значения характеристики',
  PROPERTY_VALUE_ALL_RESPONSE: 'Список значений характеристик получен',
  PROPERTY_VALUE_ALL_OPERATION: 'Получение списка всех значений характеристик',
  PROPERTY_VALUE_UPDATE_RESPONSE: 'Значение характеристики изменено',
  PROPERTY_VALUE_UPDATE_OPERATION: 'Изменение значения характеристики',
  PROPERTY_VALUE_DELETE_RESPONSE: 'Значение характеристики удалено',
  PROPERTY_VALUE_DELETE_OPERATION: 'Удаление значения характеристики',

  ROLE_NAME_EXAMPLE: 'Заказчик',
  ROLE_NAME_DESCRIPTION: 'Роль пользователя',
  ROLE_DESCRIPTION: 'Роль пользователя (пользователь, администратор и т.д.)',
  ROLE_CREATED_RESPONSE: 'Роль создана',
  ROLE_CREATE_OPERATION: 'Создание роли',
  ROLE_ALL_RESPONSE: 'Список ролей получен',
  ROLE_ALL_OPERATION: 'Получение списка всех ролей',
  ROLE_UPDATE_RESPONSE: 'Роль изменена',
  ROLE_UPDATE_OPERATION: 'Изменение роли',
  ROLE_DELETE_RESPONSE: 'Роль удалена',
  ROLE_DELETE_OPERATION: 'Удаление роли',

  TASK_NAME_EXAMPLE: 'Уборка снега',
  TASK_NAME_DESCRIPTION: 'Название задачи',
  TASK_PERIOD_START_EXAMPLE: '01.01.2024',
  TASK_PERIOD_START_DESCRIPTION: 'Начало периода',
  TASK_PERIOD_END_EXAMPLE: '31.12.2024',
  TASK_PERIOD_END_DESCRIPTION: 'Конец периода',
  TASK_DESC_EXAMPLE: 'Уборка снега перед входом',
  TASK_DESC_DESCRIPTION: 'Описание задачи',
  TASK_CREATED_RESPONSE: 'Заказы созданы ',
  TASK_CREATE_OPERATION: 'Создание плановой задачи',
  TASK_ALL_RESPONSE: 'Список задач получен',
  TASK_ALL_OPERATION: 'Получение списка всех задач',
  TASK_UPDATE_RESPONSE: 'Задача изменена',
  TASK_UPDATE_OPERATION: 'Изменение задачи',
  TASK_DELETE_RESPONSE: 'Задача удалена',
  TASK_DELETE_OPERATION: 'Удаление задачи',

  USER_EMAIL_EXAMPLE: 'email@mail.com',
  USER_EMAIL_DESCRIPTION: 'E-Mail пользователя',
  USER_ISACTIVE_EXAMPLE: true,
  USER_ISACTIVE_DESCRIPTION: 'Активна ли учетная запись',
  USER_CREATED_RESPONSE: 'Пользователь создан',
  USER_CREATE_OPERATION: 'Создание пользователя',
  USER_ORGANIZATION_CREATED_RESPONSE: 'Подрядчик создан',
  USER_ORGANIZATION_CREATE_OPERATION: 'Создание аккаунта подрядчика',
  USER_ALL_RESPONSE: 'Список пользователей получен',
  USER_ALL_OPERATION: 'Получение списка всех пользователей',
  USER_GET_RESPONSE: 'Пользователь получен',
  USER_GET_OPERATION: 'Получение одного пользователя',
  USER_UPDATE_RESPONSE: 'Пользователь изменен',
  USER_UPDATE_OPERATION: 'Изменение пользователя',
  USER_ORGANIZATION_UPDATE_RESPONSE: 'Подрядчик изменен',
  USER_ORGANIZATION_UPDATE_OPERATION: 'Изменение подрядчика',
  USER_STATUS_UPDATE_RESPONSE: 'Статус пользователя изменен',
  USER_STATUS_UPDATE_OPERATION: 'Изменение статуса пользователя',
  USER_DELETE_RESPONSE: 'Пользователь удален',
  USER_DELETE_OPERATION: 'Удаление пользователя',

  WORKING_HOURS_NAME_EXAMPLE: 'Круглосуточно',
  WORKING_HOURS_NAME_DESCRIPTION: 'Часы работы',
  WORKING_HOURS_CREATED_RESPONSE: 'Часы работы добавлены',
  WORKING_HOURS_CREATE_OPERATION: 'Добавление часов работы',
  WORKING_HOURS_ALL_RESPONSE: 'Список часов работы получен',
  WORKING_HOURS_ALL_OPERATION: 'Получение списка всех часов работы',
  WORKING_HOURS_UPDATE_RESPONSE: 'Часы работы изменены',
  WORKING_HOURS_UPDATE_OPERATION: 'Изменение часов работы',
  WORKING_HOURS_DELETE_RESPONSE: 'Часы работы удалены',
  WORKING_HOURS_DELETE_OPERATION: 'Удаление часов работы',

  PROPERTY_VALUES_EXAMPLE: '[1, 2, 3]',
  PROPERTY_VALUES_DESCRIPTION: 'ID характеристик',

  PHONE_EXAMPLE: '79001234567',
  PHONE_DESCRIPTION: 'Номер телефона',

  FILE_ALT_EXAMPLE: 'file',
  FILE_ALT_DESCRIPTION: 'Название файла',

  CREATED: 'Создан',
  SUCCESS_ROW_DELETE: 'Строка успешно удалена',

  CASCADE: 'CASCADE',

  // Services
  HISTORY_BRANCH_CREATED: 'Создан филиал #',
  HISTORY_BRANCH_UPDATED: 'Изменен филиал #',
  HISTORY_BRANCH_DELETED: 'Удален филиал #',
  HISTORY_CATEGORY_CREATED: 'Создана категория #',
  HISTORY_CATEGORY_UPDATED: 'Изменена категория #',
  HISTORY_CATEGORY_DELETED: 'Удалена категория #',
  HISTORY_CHECKPOINT_CREATED: 'Создан пункт пропуска #',
  HISTORY_CHECKPOINT_UPDATED: 'Изменен пункт пропуска #',
  HISTORY_CHECKPOINT_DELETED: 'Удален пункт пропуска #',
  HISTORY_CHECKPOINT_TYPE_CREATED: 'Создан тип пункта пропуска #',
  HISTORY_CHECKPOINT_TYPE_UPDATED: 'Изменен тип пункта пропуска #',
  HISTORY_CHECKPOINT_TYPE_DELETED: 'Удален тип пункта пропуска #',
  HISTORY_FACILITY_CREATED: 'Создан объект обслуживания #',
  HISTORY_FACILITY_UPDATED: 'Изменен объект обслуживания #',
  HISTORY_FACILITY_DELETED: 'Удален объект обслуживания #',
  HISTORY_FACILITY_TYPE_CREATED: 'Создан тип объекта обслуживания #',
  HISTORY_FACILITY_TYPE_UPDATED: 'Изменен тип объекта обслуживания #',
  HISTORY_FACILITY_TYPE_DELETED: 'Удален тип объекта обслуживания #',
  HISTORY_FILE_TYPE_CREATED: 'Создан тип файла #',
  HISTORY_FILE_TYPE_UPDATED: 'Изменен тип файла #',
  HISTORY_FILE_TYPE_DELETED: 'Удален тип файла #',
  HISTORY_FILE_CREATED: 'Создан файл #',
  HISTORY_FILE_UPDATED: 'Изменен файл #',
  HISTORY_FILE_DELETED: 'Удален файл #',
  HISTORY_GROUP_CREATED: 'Создана группа #',
  HISTORY_GROUP_UPDATED: 'Изменена группа #',
  HISTORY_GROUP_DELETED: 'Удалена группа #',
  HISTORY_NEIGHBORING_STATE_CREATED: 'Создано приграничное гос-во #',
  HISTORY_NEIGHBORING_STATE_UPDATED: 'Изменено приграничное гос-во #',
  HISTORY_NEIGHBORING_STATE_DELETED: 'Удалено приграничное гос-во #',
  HISTORY_OPERATING_MODE_CREATED: 'Создан режим работы #',
  HISTORY_OPERATING_MODE_UPDATED: 'Изменен режим работы #',
  HISTORY_OPERATING_MODE_DELETED: 'Удален режим работы #',
  HISTORY_ORDER_CREATED: 'Создан заказ',
  HISTORY_ORDER_UPDATED: 'Изменен заказ #',
  HISTORY_ORDER_NAME_UPDATED: 'Изменено название заказа',
  HISTORY_ORDER_DESC_UPDATED: 'Изменено описание заказа',
  HISTORY_ORDER_FACILITY_UPDATED: 'Изменен объект обслуживания',
  HISTORY_ORDER_EXECUTOR_UPDATED: 'Изменен исполнитель',
  HISTORY_ORDER_PLANNED_DATE_UPDATED: 'Изменена планируемая дата выполнения',
  HISTORY_ORDER_END_DATE_UPDATED: 'Изменена крайняя дата выполнения',
  HISTORY_ORDER_DELETED: 'Удален заказ #',
  HISTORY_ORDER_STATUS_CREATED: 'Создан статус заказа #',
  HISTORY_ORDER_STATUS_UPDATED: 'Изменен статус заказа',
  HISTORY_ORDER_STATUS_DELETED: 'Удален статус заказа #',
  HISTORY_ORGANIZATION_CREATED: 'Создана организация #',
  HISTORY_ORGANIZATION_UPDATED: 'Изменена организация #',
  HISTORY_ORGANIZATION_DELETED: 'Удалена организация #',
  HISTORY_ORGANIZATION_TYPE_CREATED: 'Создан тип организации #',
  HISTORY_ORGANIZATION_TYPE_UPDATED: 'Изменен тип организации #',
  HISTORY_ORGANIZATION_TYPE_DELETED: 'Удален тип организации #',
  HISTORY_PERMISSION_CREATED: 'Создано разрешение #',
  HISTORY_PERMISSION_UPDATED: 'Изменено разрешение #',
  HISTORY_PERMISSION_DELETED: 'Удалено разрешение #',
  HISTORY_PRIORITY_CREATED: 'Создан приоритет #',
  HISTORY_PRIORITY_UPDATED: 'Изменен приоритет #',
  HISTORY_PRIORITY_DELETED: 'Удален приоритет #',
  HISTORY_PROPERTY_CREATED: 'Создана характеристика #',
  HISTORY_PROPERTY_UPDATED: 'Изменена характеристика #',
  HISTORY_PROPERTY_DELETED: 'Удалена характеристика #',
  HISTORY_PROPERTY_NAME_CREATED: 'Создано название характеристики #',
  HISTORY_PROPERTY_NAME_UPDATED: 'Изменено название характеристики #',
  HISTORY_PROPERTY_NAME_DELETED: 'Удалено название характеристики #',
  HISTORY_PROPERTY_VALUE_CREATED: 'Создано значение характеристики #',
  HISTORY_PROPERTY_VALUE_UPDATED: 'Изменено значение характеристики #',
  HISTORY_PROPERTY_VALUE_DELETED: 'Удалено значение характеристики #',
  HISTORY_REPORT_CREATED: 'Создан отчет #',
  HISTORY_REPORT_UPDATED: 'Изменен отчет #',
  HISTORY_REPORT_DELETED: 'Удален отчет #',
  HISTORY_ROLE_CREATED: 'Создана роль #',
  HISTORY_ROLE_UPDATED: 'Изменена роль #',
  HISTORY_ROLE_DELETED: 'Удалена роль #',
  HISTORY_TASK_CREATED: 'Создана задача #',
  HISTORY_TASK_UPDATED: 'Изменена задача #',
  HISTORY_TASK_DELETED: 'Удалена задача #',
  HISTORY_USER_CREATED: 'Создан пользователь #',
  HISTORY_USER_ORGANIZATION_CREATED: 'Создан подрядчик #',
  HISTORY_USER_UPDATED: 'Изменен пользователь #',
  HISTORY_USER_ORGANIZATION_UPDATED: 'Изменен подрядчик #',
  HISTORY_USER_DELETED: 'Удален пользователь #',
  HISTORY_WORKING_HOURS_CREATED: 'Созданы часы работы #',
  HISTORY_WORKING_HOURS_UPDATED: 'Изменены часы работы #',
  HISTORY_WORKING_HOURS_DELETED: 'Удалены часы работы #',
  HISTORY_UPDATED: 'изменен на',

  HISTORY_ROLES_PERMISSIONS_CREATED: 'Выдано разрешение #',
  HISTORY_ROLES_PERMISSIONS_UPDATED: 'Обновлено разрешение #',
  HISTORY_ROLES_PERMISSIONS_DELETED: 'Отозвано разрешение #',
  HISTORY_ROLES_PERMISSIONS_VALUE: 'со значением',
  HISTORY_ROLES_PERMISSIONS_ROLE: 'роли #',
}
